### ISSUE TITLE
Feature: remember credentials

### ISSUE THREAD

**Issue by fusionneur** [jazzm0/ssh-daemon#15]
It would be nice to have the possibility to remember credebtials on next session (after app close)

**Comment by jazzm0** [comment]
you can save your ssh public key on the device under SshDaemon/authorized_keys. Also see https://kb.iu.edu/d/aews

**Comment by fusionneur** [comment]
What i meant, is to give user possiblity to remember the sshd password/user from withing the UI. I need to set the password everytime I want to use the app. For example on desktop machine, I use winscp where i have the predefined user/password saved but not on the app, so it makes difficult to connect easily without having this "remember credentials" option in the GUI.
