### ISSUE TITLE
rsync connection failed

### ISSUE THREAD

**Issue by dacmot** [jazzm0/ssh-daemon#16]
Hi. I had been using SshHelper from the playstore to rsync files with my phone over ssh, but it doesn't seem to work with SSH Daemon.  I use this command:

```
rsync -rvI --size-only --no-perms --delete -e 'ssh -p 8022' /home/src/path/ 192.168.1.10:/storage/3733-6438/Android/
Password authentication
Password: 
X11 forwarding request failed on channel 0
exec request failed on channel 0
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(228) [sender=3.2.3]
```

My client is Kubuntu 21.04, my phone is on LineageOS 18.1 (klte). I installed SSH Daemon from F-Droid.

Any idea how I could troubleshoot this issue? Is there a way to access the sshd logs?

Thanks.

**Comment by jazzm0** [comment]
Hi, I had a logger, but as I treated it as a dev feature I removed it. You could try to see the logs through the adb console. Not sure if Lineage supports that ... Can you ssh into the device? Or try sftp?

**Comment by dacmot** [comment]
I can SSH to the device. However, I get a very barebones terminal that doesn't even seem to have a functional shell:

```
user@desktop:~$ ssh 192.168.1.10 -p 8022
Password authentication
Password: 
X11 forwarding request failed on channel 0
/bin/sh: can't find tty fd: No such device or address
/bin/sh: warning: won't have full job control
:/ $ pwd/

:/ $ ls
ls: .: Permission denied
1|:/ $ cd /storage
/bin/sh: <stdin>[3]: cd:/storage: No such file or directory
2|:/ $ cd /storage
/bin/sh: <stdin>[4]: cd: //storage: No such file or directory
2|:/ $ exit
/bin/sh: <stdin>[5]:: inaccessible or not found
127|:/ $ 
```
I tried with -v (verbose level 1) and there's maybe one thing that could cause issues: `debug1: Sending env LANG = fr_CA.UTF-8` though there aren't any error messages.

as for SFTP with Filezilla I get a timeout after 20 seconds and it stops after two tries:
```
Réponse :	fzSftp started, protocol_version=10
Commande :	open "user@192.68.1.10" 8022
Erreur :	Connection interrompue après 20 secondes d'inactivité
Erreur :	Impossible d'établir une connexion au serveur
```

**Comment by jazzm0** [comment]
The shell is working, but the cwd is wrong. With filezilla, did you choose the sftp
![filezilla](https://user-images.githubusercontent.com/25279402/123387514-26f0e980-d598-11eb-9ff8-e9c3b58d0c96.png)
:// protocol?
