### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [jazzm0/ssh-daemon#18]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 6 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on ssh-daemon (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve ssh-daemon's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by jazzm0** [comment]
Hello, 

sure, I would like to make the project as secure as possible, so please let me know if there are any security issues.

Kind Regards

**Comment by misterAnderson90** [comment]
Dear @jazzm0,

I'm sorry for not sending this message before. I have my account flagged as spamming and I lost its access. I'm sending the six warnings that the tool reported on ssh-daemon. 3 warnings are related to the third-party class [Buffer.java](https://github.com/apache/mina-sshd/blob/master/sshd-common/src/main/java/org/apache/sshd/common/util/buffer/Buffer.java)

[Gist 01 - KeyFactory](https://gist.github.com/misterAnderson90/5194afa31e8a15360ff7f063ec6ce3c2)
[Gist 02 - KeyPair](https://gist.github.com/misterAnderson90/b8ac93edd48cf9bc13b5d546f6834111)
[Gist 03 - KeyPair](https://gist.github.com/misterAnderson90/b1198761dd01a814c486ca511b740c9b)
[Gist 04 - KeyPair](https://gist.github.com/misterAnderson90/b288b4ac7b320925aea496fc8f4b6af8)
[Gist 05 - MessageDigest](https://gist.github.com/misterAnderson90/84084ddedf8fa1472d17aa494dcdda53)
[Gist 06 - KeyPair](https://gist.github.com/misterAnderson90/978e1519e1e11e1dda595484b97252a4)

For any doubts, you can comment directly in the gists and we can clarify the issues.  

Best regards,
