### ISSUE TITLE
Can't access any files in 2.0.3; 2.0.0 works

### ISSUE THREAD

**Issue by benrg** [jazzm0/ssh-daemon#19]
On stock Android 10 on a Moto g7, SshDaemon version 2.0.3 from F-Droid doesn't work at all: I get "permission denied" trying to access any directory after logging in. Version 2.0.0 doesn't have this problem. 2.0.3 worked on Android 9 before I upgraded.

I think this was caused by ebfb430e5f7ea7f1daff56ee1a3ee7a0a4f5ebbd. I don't develop for Android, but as far as I can tell, 10 doesn't recognize `MANAGE_EXTERNAL_STORAGE`, and needs `android:requestLegacyExternalStorage="true"`. I re-added the latter to the manifest using apktool and it fixed the problem.

**Comment by jazzm0** [comment]
can you please try with the latest 2.0.7 version? I tested it on my Pixel 6 and it works.
