### ISSUE TITLE
FR: public key (only) login

### ISSUE THREAD

**Issue by trougnouf** [jazzm0/ssh-daemon#20]
It would be nice if login could be set to allow specified public key(s) only.

It looks like code might be in place per #12  , but I don't see such an option / icon.
Only port, user, password, play, and generate, like in the F-Droid screenshots (and a key icon shows up after I start the server, but it's not interactive).

I am using version 2.0.3 (latest on F-Droid) but it looks like the next versions are only translations.

**Comment by jazzm0** [comment]
Hi, when you create the file authorized_keys and put your public key in the folder SshDaemon, you should see a little key appearing on the apps screen. Then also public key auth will work. Hope this helps.
