### ISSUE TITLE
authorization by keys

### ISSUE THREAD

**Issue by OmlineEditor** [jazzm0/ssh-daemon#25]
please add the possibility of authorization by keys. using a password is not convenient

**Comment by jazzm0** [comment]
Hi, this is already possible. You should place https://github.com/jazzm0/ssh-daemon/blob/master/app/src/test/resources/authorized_keys into the folder SshDaemon. Cheers

**Comment by Offerel** [comment]
Oh my god. I try now since 2h and struggled with the format. Can you please add another info somewhere that only ssh-rsa is supported?

I had an old key inside my file with an other format and could not get it to work...

I have fixed my file now and it works as it should.
