### ISSUE TITLE
Check permissions each time app is launched

### ISSUE THREAD

**Issue by vertigo220** [jazzm0/ssh-daemon#29]
When I first launched this, it immediately took me to the permissions page to give it storage permissions (this is bad practice IMO, as it should first tell the user what it's doing). Since it didn't automatically scroll the the app in the page and flash it like most apps do, and I didn't remember the app name since I'd just installed it, I hit back to check the name. I had to actually switch back to the store to do this, since the name isn't in the app itself, and when I reopened the app, it didn't notice the lack of permissions and just carried on like normal, and only after I'd set it up and connected to it and couldn't see all my files did I realize I forgot to go back and give it permission, which now would require me to manually dig through settings to do so. Additionally, newer versions of Android will remove permissions after an app isn't used for a while by default, so even if granted initially, if a couple months goes by before it's run again, it won't have the permissions and likely won't ask for them.

**Comment by jazzm0** [comment]
this is the way android is handling this. This will be an issue for all apps accessing the filesystem, so I can't change this.
