### ISSUE TITLE
Upgrading version resets port/username/password

### ISSUE THREAD

**Issue by vertigo220** [jazzm0/ssh-daemon#37]
I had it configured then updated and everything was reset to default. It should retain the configuration.

**Comment by jazzm0** [comment]
Hi, what configuration you mean exactly? Port?

**Comment by vertigo220** [comment]
As the title says, port, username, and password are all reset to default.

**Comment by userw2891** [comment]
Yes... I was intended right now to also open a bug/feature request on this subject, so found thats already opened
We shold have in the app a SAVE buton that should save
- ssh server port
- ssh connection username
- a random generated password

maybe i shold open another feature request
- the default password shold not be "password" but a password generated on install/ first run... example android hotspot

for the rest this app is super (not tested the private key connection for now, I don't think is a real need for phone use at this moment)

**Comment by userw2891** [comment]
of course...
Maybe some people does not want this to be saved for security reason
- so a reset button can be provided
- a check mark or a togle switch instead of save button, or in addition to it... so user can chose if shold save or not

I think if no togle implemented, is safer like it is now to not save anything, to not ruin other user extra security.
thank you

**Comment by vertigo220** [comment]
@userw2891 I agree that there should be an option to toggle whether or not this info is saved. It should also probably not save by default but it should warn about this the first time it's used.

As for the default password, I don't remember that, but that's definitely not a good idea, so yeah, definitely open a new issue about it. The default password should be randomly generated and it should be either at least 6-8 random characters or 3-4 random words.

**Comment by userw2891** [comment]
we have to think that this ssh daemon is on phones not on server, no even on a home data server so:
- this server does not run permanently, just short when you need it
- you don't usually, stock on phone a lot of valuable data, maybe some notes, some pictures some pdf from internet
so:
- is good the password to be a min 8characters long, but an 4pin like on bank card is enough, so as it is now generated with the button is ok, you can manually add more if you want

Not las I do not think you need a wornnig if app, that does not save your ssh port or username, as I do not see any value in it, no security risk.

**Comment by vertigo220** [comment]
The reason a warning is preferred is because it would be annoying to set it up only to come back to the app later and find you have to set it up again, which is the whole reason for this issue. Since it shouldn't save the info by default for security reasons, it should therefore warn the user (first time only, as mentioned) about this and ask if they want to save the details. Though if the toggle is _prominently displayed_ on the main screen and not in settings, then I agree it's not really necessary.

I also agree a shorter password is _probably_ ok, but in the event someone leaves it running all the time, a longer password would offer additional security that may be helpful in such a case. And an additional few characters isn't going to make much difference in typing. I think it's better to err on the side of caution and make it a bit longer than it probably needs to be, which would help protect users, and if they really have a problem with typing in 6-8 chars, they can always delete a few of them. But better to make them reduce their security than make it reduced by default. Otherwise, if they just have 4-5 chars and leave it running all the time, it would be fairly trivial for someone to access their device's files while they're in a coffee shop, at work, etc.

**Comment by jazzm0** [comment]
Ok, after reading through all of this I decided to store port, user, the enable password flag, and the read-only flag. The password will NOT be stored however. This should be there in version 2.1.6
