### ISSUE TITLE
Can't access SD/external storage with newer version(s)

### ISSUE THREAD

**Issue by vertigo220** [jazzm0/ssh-daemon#38]
After updating from 2.0.9 to 2.1.3, I can no longer access the top level in order to select between internal and external storage on my A71 5G running Android 12.

**Comment by gitgt** [comment]
Seems the same in 2.1.5, I don't see a way to see SDcard.

**Comment by jazzm0** [comment]
Since external SD cards are less and less used, this feature will not be added, sorry.

**Comment by gitgt** [comment]
Some force to "cloud" and make phones without SD card. But many want it and buy only phones who have it. 
This IMO is srong, but means that all of us who use SD cannot use this software. Pitty.
