### ISSUE TITLE
authorized_keys not working

### ISSUE THREAD

**Issue by J-Siu** [jazzm0/ssh-daemon#43]
I put an `authorized_keys` file in "Internal storage"/SshDaemon. I see a `ssh_host_rsa_key` appears in the folder too.

However I can't connect to it with ssh keys. Password works though.

**Comment by Freso** [comment]
Can you post your `authorized_keys` file? https://github.com/jazzm0/ssh-daemon/issues/41 suggests SshDaemon will just break if `authorized_keys` contains fingerprints of unsupported types (e.g., `ssh-ed25519`). https://github.com/jazzm0/ssh-daemon/blob/761bd109207dccd1877c1c53c1c465fe1b957397/app/src/main/java/com/sshdaemon/sshd/SshPublicKeyAuthenticator.java#L45-L46 suggests only `ssh-rsa` is supported (but I don’t see that documented anywhere other than in code).

Additionally, it seems SshDaemon will reject any public keys that don’t have a password attached, which might also be what’s happening for you? Using an RSA key with a password seems to work for me, but using an RSA key without a password gives me “Permission denied (password,keyboard-interactive,publickey).”

**Comment by J-Siu** [comment]
I am using ed25519 keys. However unlike other reports, mine did not crash, just no effect. I can still login with password.

Seems the issue is from upstream mina-sshd, which in turn rely on bc-java. However it seems bc-java fixed the issue https://github.com/bcgit/bc-java/issues/592.

So I am not sure.

**Comment by jazzm0** [comment]
try version 2.1.7. That supports ed25519 keys
