### ISSUE TITLE
minSdkVersion is too high

### ISSUE THREAD

**Issue by hanpad** [jazzm0/ssh-daemon#45]
Can you make support for Android 6 (Marshmallow), please? I want to reusing my old phone for some purposes. Thank you.

**Comment by jazzm0** [comment]
I'll try, but if there are some issues, I'm sorry.

**Comment by hanpad** [comment]
Thank you very much.

**Comment by jazzm0** [comment]
should be fixed in 2.1.6

**Comment by jazzm0** [comment]
sorry, I just checked, since I use adaptive icons the minsdk version must be >= 26.

**Comment by SscSPs** [comment]
You can probably just do that under the SDK version check, did you check that out?

**Comment by SscSPs** [comment]
@hanpad  you can probably check https://play.google.com/store/apps/details?id=net.xnano.android.sshserver , it works fine on Android 6, I'm not sure if it's source is available tho
