### ISSUE TITLE
Don’t use “password” as default password

### ISSUE THREAD

**Issue by Freso** [jazzm0/ssh-daemon#46]
“password” is one of the most common passwords and anyone trying to do a dictionary-based brute-force attack will get access real easy.

Password should probably either
1) (more secure:) be generated on app startup (using whatever "Generate" uses) or
2) (less secure:) be generated first time app launches and saved (which can then be refreshed using Generate or manually changing/setting the string).

For 2), this is also related to https://github.com/jazzm0/ssh-daemon/issues/37 with the app not saving settings in between runs.

**Comment by jazzm0** [comment]
ok, will be addressed in the next version
