### ISSUE TITLE
Add a fore/background service

### ISSUE THREAD

**Issue by licaon-kter** [jazzm0/ssh-daemon#5]
...so the daemon does not get killed if the app is not in foreground.

**Comment by jazzm0** [comment]
ok, will address this soon, thanks

**Comment by fusionneur** [comment]
Is there any progress on this? It would be a great feature

**Comment by jazzm0** [comment]
I would like to do it, but I need time....

**Comment by pinckpockett** [comment]
This would take the app to another level. How is the development for this going?

**Comment by Arcoirys** [comment]
Yeah, literally the best app i found for sharing files even though it doesn't have this feature.

**Comment by vertigo220** [comment]
Agree. Would love to switch to an open-source app for this, but not being able to switch apps or turn off the display while it's running unfortunately makes it unusable for me.

**Comment by jazzm0** [comment]
Finally I got some time to do this. Please test and give feedback.

**Comment by vertigo220** [comment]
Tried testing on 2.0.9 and got some very strange results. Not sure if it's different in 2.1.0, which isn't available yet. Still disconnects when not in foreground, except if I pause it, then I can switch apps and turn off display and it stays connected or reconnects if it was disconnected, even though it shouldn't be running at all.

**Comment by jazzm0** [comment]
> Tried testing on 2.0.9 and got some very strange results. Not sure if it's different in 2.1.0, which isn't available yet. Still disconnects when not in foreground, except if I pause it, then I can switch apps and turn off display and it stays connected or reconnects if it was disconnected, even though it shouldn't be running at all.

I see version 2.1.0 in fdroid. 2.0.9 only has the password reveal feature, if the app is in background it wont work after a while.

**Comment by vertigo220** [comment]
I use Droid-ify and it's not there yet. Tried F-Droid but it crashed every time I tried accessing this app. Either way, on 2.0.9 it _does_ work in the background if the server is _not_ running (paused), and only then, so something seems very wrong. I'll have to wait until I can get 2.1.0 to see if it's still like that there, but figured you'd want to test it yourself.

**Comment by vertigo220** [comment]
Just tested with 2.1.3 and it stays running for a minute, give or take, after turning the screen off, then disconnects. After disabling battery optimizations, it seems to be doing better, so it'll require more testing, but I'd say to finish this off, the app should ask the user to disable them and take them to the page to do so.
