### ISSUE TITLE
Access to external sdcard

### ISSUE THREAD

**Issue by szmaszmo1** [jazzm0/ssh-daemon#52]
Currently "/" is leading to just /storage/emulated/0 so it is impossible to access any external sdcards like e.g. /storage/7799-806A. Since SimpleSSHD supports just "/" as "/", I guess it should be also possible here, with nice GUI (missing by Simple SSHD). Maybe there are also better approaches, as some apps like kde connect (currently sshfs seems somehow to be broken again) reach both cards at a time.

**Comment by jazzm0** [comment]
Hi, access to "/" is usually forbidden. Also most devices don't have an external card slot, so I'm sorry, this will not be implemented.
