### ISSUE TITLE
[Feature Request] Themed /Monochrome launcher app icon support

### ISSUE THREAD

**Issue by sebastien46** [jazzm0/ssh-daemon#62]
Starting with [TargetSDK 33](https://developer.android.com/about/versions/13), devices can call the [getMonochrome()](https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable#getMonochrome()) function from the [AdaptiveIconDrawable](https://developer.android.com/reference/android/graphics/drawable/AdaptiveIconDrawable) class, which can enable the app to render a user-themed / monochromatic version of it's [Drawable](https://developer.android.com/reference/kotlin/android/graphics/drawable/Drawable) icon:

![](https://developer.android.com/static/guide/practices/ui_guidelines/images/adaptive-icon-monochrome.png)

[Developer Reference Documentation](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

**Comment by sebastien46** [comment]
I've made two mockups on inkscape from the base vector for reference:

- Style 1
![logo-style1](https://github.com/jazzm0/ssh-daemon/assets/57289288/e03aa2b0-e3fd-4c4d-8bb6-38d35d7e323c)


- Style 2
![logo-style2](https://github.com/jazzm0/ssh-daemon/assets/57289288/9224c88e-7bc8-42ca-a0f5-35269be4cd04)

**Comment by jazzm0** [comment]
Hi, I choose the second option, if you don't mind. Thanks for your contribution! The release is 2.1.14.
