### ISSUE TITLE
scp/rsync support

### ISSUE THREAD

**Issue by adabru** [jazzm0/ssh-daemon#67]
Hi,
running `scp -P 8022 -i id_rsa test user@192.168.178.89:/sdcard/Music/` gives me the error:

```
scp: dest open "/sdcard/Music/": No such file or directory
scp: failed to upload file test to /sdcard/Music/
```

Running rsync gives me the error:

```
exec request failed on channel 0
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]
```

I can ssh from terminal and create files in the location `/sdcard/Music`.

**Comment by jazzm0** [comment]
Hi, this is working. I think the problem is with the path. The sftp root is the root folder of the sdcard. Meaning, that if the Music folder is in the root you should do `scp -P 8022 -i id_rsa test user@192.168.178.89:/Music/`. I just tried this with the latest version and it worked.

**Comment by adabru** [comment]
Yes you're right, thanks for the feedback! The scp command you suggested works. Rsync still doesn't work but that's not in the scope of the project imo.
