### ISSUE TITLE
Password changes everytime I stop the service

### ISSUE THREAD

**Issue by twisteros** [jazzm0/ssh-daemon#72]
I've got one password that I'm using in the device that accesses my phone's filesystem.
However, when I stop the service the password gets changed. 
Every time that happens  I need to revert it back to the old one.
Otherwise my device can't access my phone in the next run.

**Comment by jazzm0** [comment]
Hi, in this scenario I would recommend to use the password only to upload your public key to the phones SshDaemon/authorized_keys file, so you can use key based authentication. See also [public-key-authentication---what-and-why](https://www.ssh.com/academy/ssh/public-key-authentication#public-key-authentication---what-and-why?) 

Kind Regards
